before_script:
    - ./EnvironmentSetup/setup_software.sh 

stages:
    - build

# This job tests building the branch on it's own
build_feature_branch:
    stage: build
    script:
        - cd software
        # -j: compile in parallel as much as possible
        # -l: limit load to stop us running out of virtual memory
        - make -j -l 2

# Check that master will build when we merge our feature branch in
build_merged_master:
    stage: build
    script:
        - git merge origin/dev --no-commit --no-ff
        - cd software
        # -j: compile in parallel as much as possible
        # -l: limit load to stop us running out of virtual memory
        - make -j -l 2

# Compare our branch with master and check that we pass clang-format
check_formatting_master:
    stage: build
    script:
        - git merge origin/dev --no-commit --no-ff
        - ./clang-format/check_formatting.sh


