before_script:
    - ./EnvironmentSetup/setup_software.sh
    - ./EnvironmentSetup/setup_firmware.sh

stages:
    - build

# This job tests building the branch on it's own
build_feature_branch:
    stage: build
    script:
        # Make runners have their git config set properly
        - git config --global user.email "chead@chead.com"
        - git config --global user.name "Christopher Head"
        # -j: compile in parallel as much as possible
        # -l: limit load to stop us running out of virtual memory
        # process the cmake script
        - cmake -DCMAKE_BUILD_TYPE=Debug -Bcmake-build-debug -H.
        # build and test software from top level
        - cmake --build cmake-build-debug --target all -- -C software -j 4
        - software/bin/software_test
        # build and test firmware from top level
        - cmake --build cmake-build-debug --target all -- -C firmware -j 4
        - cmake-build-debug/firmware/test/fw_test

# Check that dev will build when we merge our feature branch in
build_merged_master:
    stage: build
    script:
        # Make runners have their git config set properly
        - git config --global user.email "chead@chead.com"
        - git config --global user.name "Christopher Head"
        - git merge origin/dev --no-commit --no-ff
        # -j: compile in parallel as much as possible
        # -l: limit load to stop us running out of virtual memory
        # process the cmake script
        - cmake -DCMAKE_BUILD_TYPE=Debug -Bcmake-build-debug -H.
        # build and test software from top level
        - cmake --build cmake-build-debug --target all -- -C software -j 4
        - software/bin/software_test
        # build and test firmware from top level
        - cmake --build cmake-build-debug --target all -- -C firmware -j 4
        - cmake-build-debug/firmware/test/fw_test

# Merge our branch into dev and check that we still pass clang-format
check_formatting_master:
    stage: build
    script:
        # Make runners have their git config set properly
        - git config --global user.email "chead@chead.com"
        - git config --global user.name "Christopher Head"
        - git merge origin/dev --no-commit --no-ff
        - ./clang-format/fix_formatting.sh dev


